service: rubycats-com
image: rubycats-com/rubycats-com
servers:
  web:
    hosts:
      - rubycats.com
    options:
      "add-host": host.docker.internal:host-gateway
proxy:
  ssl: true
  host: rubycats.com
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_PASSWORD
    - OMNIAUTH_GITHUB_APP_ID
    - OMNIAUTH_GITHUB_APP_SECRET
    - SENTRY_DSN
  clear:
    RAILS_ENV: production
    SOLID_QUEUE_IN_PUMA: true
    SITE_NAME: RubyCats
    SITE_URL: https://rubycats.com
    DATABASE_HOST: host.docker.internal
    DATABASE_PORT: 5432
    DATABASE_USER: rubycats-com
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "rubycats-com-storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
  remote: ssh://rubycats-com@rubycats.com
  local: false
  secrets:
    - GITHUB_TOKEN
ssh:
  user: rubycats-com
