service: rubycats
image: rubycats-com/rubycats
servers:
  web:
    hosts:
      - rubycats.com
    options:
      "add-host": host.docker.internal:host-gateway
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    RAILS_ENV: production
    SITE_NAME: RubyCats
    SITE_URL: https://rubycats.com
    DB_HOST: host.docker.internal
    DB_PORT: 5432
    DB_NAME: rubycats-com
    DB_USER: rubycats-com
  secret:
    - RAILS_MASTER_KEY
    - DB_PASSWORD
    - OMNIAUTH_GITHUB_APP_ID
    - OMNIAUTH_GITHUB_APP_SECRET
    - SENTRY_DSN
ssh:
  user: rubycats-com
builder:
  multiarch: false
  secrets:
    - GITHUB_TOKEN
  remote:
    arch: amd64
    host: ssh://rubycats-com@rubycats.com
traefik:
  host_port: 127.0.0.1:8091
