name: cd
on:
  push:
    branches: [ 'main' ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_BUILDKIT: 1
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OMNIAUTH_GITHUB_APP_ID: ${{ secrets.OMNIAUTH_GITHUB_APP_ID }}
      OMNIAUTH_GITHUB_APP_SECRET: ${{ secrets.OMNIAUTH_GITHUB_APP_SECRET }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Set ssh key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Run deploy command
        run: |
          bundle exec kamal deploy
      - uses: beacon-biosignals/job-context@v1
        id: job-data
      - name: Jarvis report
        uses: appleboy/telegram-action@v1.0.0
        if: success() || failure()
        with:
          to: ${{ secrets.JARVIS_TELEGRAM_REPORT_TO }}
          token: ${{ secrets.JARVIS_TELEGRAM_TOKEN }}
          disable_notification: ${{ job.status == 'success' && true || false }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ${{ job.status == 'success' && '🟢' || '🔴' }} *CI/CD:* [${{ job.status == 'success' && 'SUCCESS' || 'FAILURE' }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.job-data.outputs.id }}) *${{ github.workflow }}:${{ github.job }}* workflow, triggered by: _${{ github.actor }}_
            Branch: `${{ github.ref_name }}`, Repository: `${{ github.repository }}`
