name: CD
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_BUILDKIT: 1
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OMNIAUTH_GITHUB_APP_ID: ${{ secrets.OMNIAUTH_GITHUB_APP_ID }}
      OMNIAUTH_GITHUB_APP_SECRET: ${{ secrets.OMNIAUTH_GITHUB_APP_SECRET }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Set ssh key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run deploy command
        run: |
          bundle exec kamal env push -d ci
          bundle exec kamal deploy -d ci
          bundle exec kamal app exec -r web -p --reuse 'bin/rails db:migrate' -d ci
